#ifndef _DEV_STS_SERVO_CONFIG_H_
#define _DEV_STS_SERVO_CONFIG_H_

/* Protocol */
#define STS_SERVO_HEADER_1 (0xFFU)
#define STS_SERVO_HEADER_2 (0xFFU)
#define STS_SERVO_BROADCAST_ID (0xFEU)
#define STS_SERVO_MAX_ID (0xFDU)

/* Instructions */
#define STS_SERVO_INST_PING (0x01U)
#define STS_SERVO_INST_READ (0x02U)
#define STS_SERVO_INST_WRITE (0x03U)
#define STS_SERVO_INST_REG_WRITE (0x04U)
#define STS_SERVO_INST_ACTION (0x05U)
#define STS_SERVO_INST_RESET (0x06U)
#define STS_SERVO_INST_SYNC_READ (0x82U)
#define STS_SERVO_INST_SYNC_WRITE (0x83U)

/* Packet and queue sizing */
#define STS_SERVO_PACKET_OVERHEAD (6U)
#define STS_SERVO_MAX_PARAM_LEN (240U)
#define STS_SERVO_TX_BUF_SIZE (256U)
#define STS_SERVO_RX_TMP_BUF_SIZE (32U)
#define STS_SERVO_CMD_QUEUE_SIZE (4U)
#define STS_SERVO_RSP_QUEUE_SIZE (12U)

/* Timing */
#define STS_SERVO_DEFAULT_TIMEOUT_MS (20U)

/* Fault flags */
#define STS_SERVO_FAULT_NONE (0x00000000UL)
#define STS_SERVO_FAULT_OVER_TEMP (0x00000001UL)
#define STS_SERVO_FAULT_UNDER_VOLTAGE (0x00000002UL)
#define STS_SERVO_FAULT_OVER_VOLTAGE (0x00000004UL)
#define STS_SERVO_FAULT_OVER_LOAD (0x00000008UL)
#define STS_SERVO_FAULT_OVER_CURRENT (0x00000010UL)
#define STS_SERVO_FAULT_POSITION_ERROR (0x00000020UL)
#define STS_SERVO_FAULT_BUS_TIMEOUT (0x00000040UL)
#define STS_SERVO_FAULT_STATUS_ERROR (0x00000080UL)

/* Protection decision is confirmed by the task layer to avoid transient alarms
 * directly cutting torque during command execution or commissioning.
 */
#define STS_SERVO_PROTECT_DISABLE_TORQUE_FAULTS (STS_SERVO_FAULT_NONE)

/* Memory table addresses for magnetic encoder STS servos. */
#define STS_SERVO_ADDR_ID (0x05U)
#define STS_SERVO_ADDR_BAUDRATE (0x06U)
#define STS_SERVO_ADDR_RETURN_DELAY (0x07U)
#define STS_SERVO_ADDR_RESPONSE_LEVEL (0x08U)

#define STS_SERVO_ADDR_MIN_POSITION (0x09U)
#define STS_SERVO_ADDR_MAX_POSITION (0x0BU)
#define STS_SERVO_ADDR_MAX_TEMPERATURE (0x0DU)
#define STS_SERVO_ADDR_MAX_VOLTAGE (0x0EU)
#define STS_SERVO_ADDR_MIN_VOLTAGE (0x0FU)
#define STS_SERVO_ADDR_MAX_TORQUE (0x10U)

#define STS_SERVO_ADDR_MODE (0x21U)
#define STS_SERVO_ADDR_TORQUE_ENABLE (0x28U)
#define STS_SERVO_ADDR_ACC (0x29U)
#define STS_SERVO_ADDR_TARGET_POSITION (0x2AU)
#define STS_SERVO_ADDR_RUNNING_TIME (0x2CU)
#define STS_SERVO_ADDR_RUNNING_SPEED (0x2EU)
#define STS_SERVO_ADDR_TORQUE_LIMIT (0x30U)

#define STS_SERVO_ADDR_CURRENT_POSITION (0x38U)
#define STS_SERVO_ADDR_CURRENT_SPEED (0x3AU)
#define STS_SERVO_ADDR_CURRENT_LOAD (0x3CU)
#define STS_SERVO_ADDR_CURRENT_VOLTAGE (0x3EU)
#define STS_SERVO_ADDR_CURRENT_TEMP (0x3FU)
#define STS_SERVO_ADDR_STATUS (0x41U)
#define STS_SERVO_ADDR_MOVING (0x42U)
#define STS_SERVO_ADDR_CURRENT_CURRENT (0x45U)

/* Common values */
#define STS_SERVO_MODE_POSITION (0U)
#define STS_SERVO_TORQUE_DISABLE (0U)
#define STS_SERVO_TORQUE_ENABLE (1U)
#define STS_SERVO_TORQUE_DAMPING (2U)
#define STS_SERVO_TORQUE_CALIBRATE (128U)

/* Default device parameters */
#define STS_SERVO_POSITION_MIN_DEFAULT (0)
#define STS_SERVO_POSITION_MAX_DEFAULT (4095)
#define STS_SERVO_POSITION_ZERO_DEFAULT (2048)
#define STS_SERVO_POSITION_PER_RAD_DEFAULT (651.8986206f)
#define STS_SERVO_SPEED_DEFAULT (1200U)
#define STS_SERVO_ACC_DEFAULT (50U)

/* Conservative protection defaults.
 * Voltage uses the STS 0.1 V unit, temperature uses degrees Celsius.
 */
#define STS_SERVO_MAX_TEMPERATURE_DEFAULT (65U)
#define STS_SERVO_MIN_VOLTAGE_DEFAULT (60U)
#define STS_SERVO_MAX_VOLTAGE_DEFAULT (84U)
#define STS_SERVO_MAX_LOAD_DEFAULT (800U)
#define STS_SERVO_MAX_CURRENT_DEFAULT (1500U)
#define STS_SERVO_MAX_POSITION_ERROR_DEFAULT (300U)

#endif /* _DEV_STS_SERVO_CONFIG_H_ */
