#ifndef _DEV_BRUSH_MOTOR_CONFIG_H_
#define _DEV_BRUSH_MOTOR_CONFIG_H_

#define RPM_FILTER_ALPHA (1.f) // for low-pass filter of current_rpm
#define RPM_DEADZONE (2.0f)

#define MOTOR_BLOCK_TARGET_RPM_THRESHOLD (20.0f)
#define MOTOR_BLOCK_CURRENT_RPM_THRESHOLD (5.0f)
#define MOTOR_BLOCK_FORCED_RPM_THRESHOLD (20.0f)
#define MOTOR_BLOCK_DUTY_THRESHOLD (60.0f)
#define MOTOR_BLOCK_MAX_CNT_DEFAULT (100U)
#define MOTOR_BLOCK_AUTO_CLEAR_CNT (500U)

#endif /* _DEV_BRUSH_MOTOR_CONFIG_H_ */
