#pragma once

#include "k1muse_ai_runtime/backends/vision_backend.hpp"

#include <cstdint>
#include <string>

namespace k1muse_ai_runtime
{

/// Deterministic mock pose-estimation backend.
/// Returns person detections with stable IDs simulating
/// yolov8n-pose output (bounding box only; keypoints are
/// generated by the VisionPipeline's pose callback layer).
class MockPoseBackend : public VisionBackend
{
public:
  MockPoseBackend();

  const std::string & name() const override;

  void load() override;
  void unload() override;
  bool loaded() const override;

  void warmup() override;

  FrameResult infer(
    const std::string & frame_id,
    uint32_t width, uint32_t height,
    const std::string & encoding,
    const uint8_t * data, size_t data_size,
    uint32_t step) override;

  void reset() override;

  void set_mock_person_count(uint32_t count);
  void set_mock_score(float score);
  void set_mock_delay_ms(int ms); // simulate inference latency

private:
  bool loaded_{false};
  uint32_t person_count_{2};
  float mock_score_{0.85f};
  int mock_delay_ms_{0};
};

}  // namespace k1muse_ai_runtime
