#ifndef _MDL_PERIPHERAL_CONFIG_H_
#define _MDL_PERIPHERAL_CONFIG_H_

#include <stdint.h>

#define PERIPHERAL_TASK_PERIOD_MS (10U)
#define PERIPHERAL_STATUS_PERIOD_MS (50U)
#define PERIPHERAL_STATUS_PHASE_MS (10U)

#define GAS_SENSOR_DETECTED_LEVEL (0U)

#define SHT31_MEASURE_PERIOD_MS (1000U)
#define SHT31_MEASURE_WAIT_MS (10U)
#define SHT31_ERROR_LIMIT (3U)

#define POWER_ADC_REF_MV (2500U)
#define POWER_ADC_MAX_RAW (4095U)
#define POWER_ADC_SAMPLE_COUNT (16U)
#define POWER_VOLTAGE_SCALE_NUM (49U)
#define POWER_VOLTAGE_SCALE_DEN (10U)
#define POWER_VOLTAGE_CAL_NUM (10640U)
#define POWER_VOLTAGE_CAL_DEN (9535U)
#define POWER_VOLTAGE_FILTER_SHIFT (4U)

#define POWER_LOW_THRESHOLD_MV (10300U)
#define POWER_CRITICAL_THRESHOLD_MV (9800U)
#define POWER_FAULT_THRESHOLD_MV (9000U)
#define POWER_STATE_CONFIRM_MS (5000U)

#endif /* _MDL_PERIPHERAL_CONFIG_H_ */
